//ipth_waptypes.h
/******************************************************************************
 * ipth_waptypes.h - defines the public interface of client 6.x WAP TYPES protoypes.
 *
 * Copyright (c) 2003-2008 InnoPath Software, Inc. All rights reserved.
 *
 * Legal Statements
 *
 * THE SOFTWARE AND ANY MATERIALS PROVIDED BY INNOPATH ARE PROVIDED ON AN "AS
 * IS" BASIS WITHOUT ANY REPRESENTATIONS, WARRANTIES OR CONDITIONS OF ANY KIND,
 * WHETHER EXPRESS, IMPLIED, STATUTORY, OUT OF A COURSE OF DEALING OR USAGE,
 * TRADE OR OTHERWISE INCLUDING ANY IMPLIED WARRANTIES OR CONDITIONS OF
 * MERCHANTABILITY, MERCHANTABLE QUALITY, FITNESS FOR ANY PARTICULAR PURPOSE
 * OR USE, TITLE, OR NON-INFRINGEMENT. INNOPATH DOES NOT REPRESENT OR WARRANT
 * THAT THE SOFTWARE OR ANY MATERIALS WILL BE FREE OF DEFECTS, UNINTERRUPTED,
 * ACCURATE, COMPLETE, CURRENT, STABLE, BUG-FREE, ERROR-FREE, OR AVAILABLE AT
 * ANY TIME.
 *
 * TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL INNOPATH BE LIABLE
 * FOR ANY DIRECT, INDIRECT, CONSEQUENTIAL, INCIDENTAL, SPECIAL, RELIANCE,
 * PUNITIVE OR OTHER DAMAGES OR EXPENSES OF ANY KIND, INCLUDING BUT NOT LIMITED
 * TO ANY LOSS OF PROFITS OR REVENUE, LOST SAVINGS, INTERRUPTED BUSINESS, LOST
 * BUSINESS, LOST BUSINESS OPPORTUNITIES, LOST DATA, LOST GOODWILL, LOSS FROM
 * WORK STOPPAGE, COSTS OF OVERHEAD, COSTS OF COVER, LOSS OF ANTICIPATED
 * BENEFITS HEREUNDER, ARISING OUT OF OR RELATED TO THIS AGREEMENT, HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, EVEN IF INNOPATH HAS BEEN ADVISED OF
 * THE POSSIBILITY OF SUCH DAMAGES, AND NOTWITHSTANDING THE FAILURE OF THE
 * ESSENTIAL PURPOSE OF ANY LIMITED REMEDY STATED HEREIN.
 *****************************************************************************/

#ifndef __IPTH_WAPTYPES_H__
#define __IPTH_WAPTYPES_H__

#ifdef	__cplusplus
extern "C" {
#endif

#define    IPTH_WAP_APP_REG_PATH    "\\Program Files\\InnoPath ActiveCare Client\\dme_main.exe"
#define	   IPTH_WAP_APP_ARG			"/wap_push"
#define    IPTH_WAP_APP_ID          "x-wap-innopath:dm"
#define	   IPTH_WAP_TIMEOUT			10000
#define    IPTH_WAP_CONTENT_TYPE_NOTIFICATION		"x-application/vnd.innopath.notification"
#define    IPTH_WAP_CONTENT_TYPE_BOOTSTRAP			"x-application/vnd.innopath.dm+wbxml"
#if 0
#define    IPTH_STD_WAP_CONTENT_TYPE_BOOTSTRAP		"application/vnd.syncml.dm+wbxml"
#define	   IPTH_STD_WAP_APP_ID		"x-wap-application:syncml.dm"
#define    IPTH_STD_WAP_CONTENT_TYPE_NOTIFICATION	"application/vnd.syncml.notification"
#endif

#ifdef	__cplusplus
}
#endif
#endif /* __IPTH_WAPTYPES_H__ */
